"""Initial models

Revision ID: c96c6c0a4a26
Revises: 
Create Date: 2026-01-14 18:55:09.825963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96c6c0a4a26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audio_filename', sa.String(length=500), nullable=True),
    sa.Column('audio_duration', sa.Float(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('soap_note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADING', 'PROCESSING', 'TRANSCRIBING', 'GENERATING', 'COMPLETED', 'FAILED', name='consultationstatus'), nullable=False),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_created_at'), 'consultations', ['created_at'], unique=False)
    op.create_index(op.f('ix_consultations_id'), 'consultations', ['id'], unique=False)
    op.create_index(op.f('ix_consultations_status'), 'consultations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultations_status'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_created_at'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
