"""add_patient_doctor_names

Revision ID: 1331ec9b2464
Revises: c96c6c0a4a26
Create Date: 2026-03-01 12:18:53.705885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1331ec9b2464'
down_revision = 'c96c6c0a4a26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('patient_name', sa.String(length=200), nullable=True))
    op.add_column('consultations', sa.Column('doctor_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'doctor_name')
    op.drop_column('consultations', 'patient_name')
    # ### end Alembic commands ###
