/**
 * Export utilities for consultations
 * Supports text, PDF, and formatted exports
 */

import type { Consultation } from '../types'
import jsPDF from 'jspdf'

/**
 * Strip markdown syntax from text for plain-text rendering in PDF
 */
function stripMarkdown(text: string): string {
  return text
    .replace(/^#{1,6}\s+/gm, '')        // remove headings
    .replace(/\*\*(.+?)\*\*/g, '$1')    // **bold**
    .replace(/\*(.+?)\*/g, '$1')        // *italic*
    .replace(/^[-*]\s+/gm, '• ')        // bullet points
    .replace(/^\s{2,}[-*]\s+/gm, '  – ')// nested bullets
    .trim()
}

/**
 * Download consultation as a formatted PDF report
 */
export function downloadAsPDF(consultation: Consultation): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const margin = 20
  const contentW = pageW - margin * 2
  let y = margin

  const addText = (text: string, size: number, style: 'normal' | 'bold' = 'normal', color = '#111827') => {
    doc.setFontSize(size)
    doc.setFont('helvetica', style)
    doc.setTextColor(color)
    const lines = doc.splitTextToSize(text, contentW) as string[]
    lines.forEach(line => {
      if (y + 6 > pageH - margin) {
        doc.addPage()
        y = margin
      }
      doc.text(line, margin, y)
      y += size * 0.45
    })
  }

  const addSpacer = (h = 4) => { y += h }
  const addDivider = () => {
    if (y + 2 > pageH - margin) { doc.addPage(); y = margin }
    doc.setDrawColor('#D1D5DB')
    doc.line(margin, y, pageW - margin, y)
    y += 4
  }

  // ── Header ──────────────────────────────────────────────
  doc.setFillColor('#2563EB')
  doc.rect(0, 0, pageW, 18, 'F')
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor('#FFFFFF')
  doc.text('Clinical Consultation Report', margin, 12)
  y = 26

  // ── Meta block ──────────────────────────────────────────
  addText('Patient Name:', 9, 'bold', '#6B7280')
  addText(consultation.patient_name || 'Not specified', 10, 'normal', '#111827')
  addSpacer(2)
  addText('Doctor Name:', 9, 'bold', '#6B7280')
  addText(consultation.doctor_name || 'Not specified', 10, 'normal', '#111827')
  addSpacer(2)
  addText('Date & Time:', 9, 'bold', '#6B7280')
  addText(new Date(consultation.created_at).toLocaleString(), 10, 'normal', '#111827')
  addSpacer(2)
  addText('Consultation ID:', 9, 'bold', '#6B7280')
  addText(String(consultation.id), 10, 'normal', '#111827')
  addSpacer(4)
  addDivider()

  // ── SOAP Note ───────────────────────────────────────────
  if (consultation.soap_note) {
    addText('SOAP NOTE', 12, 'bold', '#1D4ED8')
    addSpacer(2)
    addText(stripMarkdown(consultation.soap_note), 9, 'normal', '#111827')
    addSpacer(6)
    addDivider()
  }

  // ── Transcript ──────────────────────────────────────────
  if (consultation.transcript) {
    addText('TRANSCRIPT', 12, 'bold', '#1D4ED8')
    addSpacer(2)
    addText(consultation.transcript, 9, 'normal', '#111827')
    addSpacer(6)
    addDivider()
  }

  // ── Footer ──────────────────────────────────────────────
  addSpacer(2)
  addText(`Generated on ${new Date().toLocaleString()} by Clinical Documentation Assistant`, 8, 'normal', '#9CA3AF')

  doc.save(`consultation-${consultation.id}-report.pdf`)
}

/**
 * Format consultation data for export
 */
export function formatConsultationForExport(consultation: Consultation): string {
  const header = `CLINICAL CONSULTATION RECORD
${'='.repeat(60)}

Consultation ID: ${consultation.id}
Date: ${new Date(consultation.created_at).toLocaleString()}
Status: ${consultation.status.toUpperCase()}
${consultation.processing_time ? `Processing Time: ${consultation.processing_time.toFixed(1)}s` : ''}

${'='.repeat(60)}
`

  const transcript = consultation.transcript
    ? `\nTRANSCRIPT
${'-'.repeat(60)}

${consultation.transcript}

`
    : ''

  const soapNote = consultation.soap_note
    ? `\nSOAP NOTE
${'-'.repeat(60)}

${consultation.soap_note}

`
    : ''

  const footer = `\n${'='.repeat(60)}
Generated on: ${new Date().toLocaleString()}
Generated by: Clinical Documentation Assistant
${'='.repeat(60)}`

  return header + transcript + soapNote + footer
}

/**
 * Download consultation as text file
 */
export function downloadAsText(consultation: Consultation): void {
  const content = formatConsultationForExport(consultation)
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `consultation-${consultation.id}-${Date.now()}.txt`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Download SOAP note only as text file
 */
export function downloadSOAPAsText(consultation: Consultation): void {
  if (!consultation.soap_note) {
    throw new Error('No SOAP note available')
  }

  const header = `SOAP NOTE - Consultation #${consultation.id}
Date: ${new Date(consultation.created_at).toLocaleString()}
${'='.repeat(60)}

`

  const content = header + consultation.soap_note

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `soap-note-${consultation.id}-${Date.now()}.txt`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Download transcript only as text file
 */
export function downloadTranscriptAsText(consultation: Consultation): void {
  if (!consultation.transcript) {
    throw new Error('No transcript available')
  }

  const header = `TRANSCRIPT - Consultation #${consultation.id}
Date: ${new Date(consultation.created_at).toLocaleString()}
${'='.repeat(60)}

`

  const content = header + consultation.transcript

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `transcript-${consultation.id}-${Date.now()}.txt`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Copy text to clipboard
 */
export async function copyToClipboard(text: string): Promise<void> {
  try {
    await navigator.clipboard.writeText(text)
  } catch (err) {
    // Fallback for older browsers
    const textArea = document.createElement('textarea')
    textArea.value = text
    textArea.style.position = 'fixed'
    textArea.style.left = '-999999px'
    document.body.appendChild(textArea)
    textArea.focus()
    textArea.select()
    try {
      document.execCommand('copy')
    } catch (err) {
      throw new Error('Failed to copy to clipboard')
    }
    document.body.removeChild(textArea)
  }
}

/**
 * Copy SOAP note to clipboard
 */
export async function copySOAPToClipboard(consultation: Consultation): Promise<void> {
  if (!consultation.soap_note) {
    throw new Error('No SOAP note available')
  }
  await copyToClipboard(consultation.soap_note)
}

/**
 * Copy transcript to clipboard
 */
export async function copyTranscriptToClipboard(consultation: Consultation): Promise<void> {
  if (!consultation.transcript) {
    throw new Error('No transcript available')
  }
  await copyToClipboard(consultation.transcript)
}

/**
 * Print consultation (opens browser print dialog)
 */
export function printConsultation(consultation: Consultation): void {
  const content = formatConsultationForExport(consultation)

  // Create a new window for printing
  const printWindow = window.open('', '_blank')
  if (!printWindow) {
    throw new Error('Could not open print window. Please check your popup blocker settings.')
  }

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>Consultation #${consultation.id}</title>
      <style>
        body {
          font-family: 'Courier New', monospace;
          padding: 20px;
          max-width: 800px;
          margin: 0 auto;
          line-height: 1.6;
        }
        h1 {
          font-size: 18px;
          margin-bottom: 10px;
        }
        pre {
          white-space: pre-wrap;
          word-wrap: break-word;
          font-family: 'Courier New', monospace;
          font-size: 12px;
        }
        @media print {
          body {
            padding: 0;
          }
        }
      </style>
    </head>
    <body>
      <pre>${content}</pre>
    </body>
    </html>
  `)

  printWindow.document.close()
  printWindow.focus()

  // Wait for content to load before printing
  setTimeout(() => {
    printWindow.print()
  }, 250)
}

/**
 * Generate HTML for email
 */
export function generateEmailHTML(consultation: Consultation): string {
  const content = formatConsultationForExport(consultation)
  return `
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        pre { white-space: pre-wrap; word-wrap: break-word; background: #f4f4f4; padding: 10px; border-radius: 4px; }
      </style>
    </head>
    <body>
      <pre>${content}</pre>
    </body>
    </html>
  `
}

/**
 * Open email client with consultation data
 */
export function emailConsultation(consultation: Consultation, recipientEmail: string = ''): void {
  const subject = `Consultation #${consultation.id} - ${new Date(consultation.created_at).toLocaleDateString()}`
  const body = formatConsultationForExport(consultation)

  const mailtoLink = `mailto:${recipientEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
  window.location.href = mailtoLink
}
